image: golang:1.13.5-alpine3.11 # utilizar misma imagen de docker que en el dockerfile

clone:
  depth: full

definitions:
  caches:
    sonar: ~/.sonar/cache
  steps:
    - step: &build-test-sonarcloud
        name: Build, test and analyze on SonarCloud
        caches:
          - sonar
        script:
          - source JenkinsParams
          - export REPOSITORY_NAME=$(echo $BITBUCKET_REPO_FULL_NAME |  sed 's|.*/||')
          # - go test
          - pipe: sonarsource/sonarcloud-scan:1.3.0
            variables:
              EXTRA_ARGS: >
                -Dsonar.projectKey=\"${BITBUCKET_PROJECT_KEY}_${REPOSITORY_NAME}\" 
                -Dsonar.projectName=\"${BITBUCKET_PROJECT_KEY}_${REPOSITORY_NAME}\" 
                -Dsonar.projectVersion=\"$VERSION\" 
                -Dsonar.sources=\"$SCAN_SOURCE\" 
                -Dsonar.exclusions=\"$SCAN_EXCLUDE_FILES\"
                -Dsonar.lang.patterns.cobol=**/*
              # -Dsonar.cobol.copy.directories=COBOL/cpy
              # -Dsonar.cobol.copy.suffixes=cpy,cob
              # -Dsonar.go.coverage.reportPaths=\"$SCAN_COVERAGE_REPORT\"
    - step: &check-quality-gate-sonarcloud
        name: Check the Quality Gate on SonarCloud
        caches:
          - sonar
        script:
          - pipe: sonarsource/sonarcloud-quality-gate:0.1.6

pipelines:
  custom: # Pipelines that can only be triggered manually
    sonar:
      - step: *build-test-sonarcloud
      - step: *check-quality-gate-sonarcloud
  branches:
    development:
      - step: *build-test-sonarcloud
      - step: *check-quality-gate-sonarcloud
  pull-requests:
    "**":
      - step: *build-test-sonarcloud
      - step: *check-quality-gate-sonarcloud
